In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import matplotlib as mlt

In [2]:
torch.manual_seed(1)
x_data=torch.FloatTensor([[1],[2],[3],[4],[5]])
t_data=torch.FloatTensor([[3],[5],[7],[9],[11]])

In [3]:
model=nn.Linear(1,1)    # input_dim=1, output_dim=1
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [4]:
optimizer=optim.SGD(model.parameters(), lr=0.01)

In [5]:
nb_epochs=20000

for epoch in range(nb_epochs):
    prediction=model(x_data)
    cost=F.mse_loss(prediction, t_data)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 400 == 0:
        print('Epoch : ', epoch, 'Cost : ',cost.item())

Epoch :  0 Cost :  39.16685104370117
Epoch :  400 Cost :  0.01109258271753788
Epoch :  800 Cost :  0.0007385412463918328
Epoch :  1200 Cost :  4.91717473778408e-05
Epoch :  1600 Cost :  3.276181814726442e-06
Epoch :  2000 Cost :  2.1860606125301274e-07
Epoch :  2400 Cost :  1.4702209227834828e-08
Epoch :  2800 Cost :  9.986707016906848e-10
Epoch :  3200 Cost :  1.0809344391793374e-10
Epoch :  3600 Cost :  5.426272625674855e-11
Epoch :  4000 Cost :  5.426272625674855e-11
Epoch :  4400 Cost :  5.426272625674855e-11
Epoch :  4800 Cost :  5.426272625674855e-11
Epoch :  5200 Cost :  5.426272625674855e-11
Epoch :  5600 Cost :  5.426272625674855e-11
Epoch :  6000 Cost :  5.426272625674855e-11
Epoch :  6400 Cost :  5.426272625674855e-11
Epoch :  6800 Cost :  5.426272625674855e-11
Epoch :  7200 Cost :  5.426272625674855e-11
Epoch :  7600 Cost :  5.426272625674855e-11
Epoch :  8000 Cost :  5.426272625674855e-11
Epoch :  8400 Cost :  5.426272625674855e-11
Epoch :  8800 Cost :  5.426272625674855e-

In [6]:
new_data=torch.FloatTensor([[10.0]])
y_pred=model(new_data)
print(y_pred)
print(list(model.parameters()))

tensor([[21.0000]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([1.0000], requires_grad=True)]


In [7]:
x_train =  torch.FloatTensor([[73,  80,  75], 
[93,  88, 93], 
[89,  91, 80], 
[96,  98, 100], 
[73,  66, 70]]) 
y_train =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [8]:
model=nn.Linear(3,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True), Parameter containing:
tensor([0.3462], requires_grad=True)]


In [9]:
optimizer=optim.SGD(model.parameters(), lr=1e-6)

In [10]:
nb_epochs=20000
for epoch in range(nb_epochs):
    prediction=model(x_train)
    cost=F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 400 == 0:
        print('Epoch : ', epoch, 'Cost : ', cost.item())
        print('Prmaters:', list(model.parameters()))

Epoch :  0 Cost :  41675.6171875
Prmaters: [Parameter containing:
tensor([[-0.0771,  0.3058, -0.5091]], requires_grad=True), Parameter containing:
tensor([0.3467], requires_grad=True)]
Epoch :  400 Cost :  5.383914470672607
Prmaters: [Parameter containing:
tensor([[0.6968, 1.0695, 0.2519]], requires_grad=True), Parameter containing:
tensor([0.3556], requires_grad=True)]
Epoch :  800 Cost :  5.277735233306885
Prmaters: [Parameter containing:
tensor([[0.7010, 1.0646, 0.2526]], requires_grad=True), Parameter containing:
tensor([0.3556], requires_grad=True)]
Epoch :  1200 Cost :  5.174044132232666
Prmaters: [Parameter containing:
tensor([[0.7051, 1.0597, 0.2534]], requires_grad=True), Parameter containing:
tensor([0.3556], requires_grad=True)]
Epoch :  1600 Cost :  5.072737693786621
Prmaters: [Parameter containing:
tensor([[0.7092, 1.0549, 0.2541]], requires_grad=True), Parameter containing:
tensor([0.3557], requires_grad=True)]
Epoch :  2000 Cost :  4.9737868309021
Prmaters: [Parameter co

In [11]:
print(list(model.parameters()))
new_data=torch.FloatTensor([[80,80,90]])
y_pred=model(new_data)
print(y_pred)

[Parameter containing:
tensor([[0.8652, 0.8891, 0.2638]], requires_grad=True), Parameter containing:
tensor([0.3560], requires_grad=True)]
tensor([[164.4436]], grad_fn=<AddmmBackward0>)


# class 사용 single regression

In [12]:
torch.manual_seed(1)
x_data=torch.FloatTensor([[1],[2],[3],[4],[5]])
t_data=torch.FloatTensor([[3],[5],[7],[9],[11]])

In [13]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(1,1)

    def forward(self, x):
        return self.linear(x)

In [14]:
model=LinearRegressionModel()
print(list(model.parameters()))
optimizer=optim.SGD(model.parameters(), lr=0.01)

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [15]:
nb_epochs=20000
for epoch in range(nb_epochs):
    prediction=model(x_data)
    cost=F.mse_loss(prediction, t_data)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 400 == 0 :
        print('Epoch : ', epoch, 'Cost : ' ,cost)

Epoch :  0 Cost :  tensor(39.1669, grad_fn=<MseLossBackward0>)
Epoch :  400 Cost :  tensor(0.0111, grad_fn=<MseLossBackward0>)
Epoch :  800 Cost :  tensor(0.0007, grad_fn=<MseLossBackward0>)
Epoch :  1200 Cost :  tensor(4.9172e-05, grad_fn=<MseLossBackward0>)
Epoch :  1600 Cost :  tensor(3.2762e-06, grad_fn=<MseLossBackward0>)
Epoch :  2000 Cost :  tensor(2.1861e-07, grad_fn=<MseLossBackward0>)
Epoch :  2400 Cost :  tensor(1.4702e-08, grad_fn=<MseLossBackward0>)
Epoch :  2800 Cost :  tensor(9.9867e-10, grad_fn=<MseLossBackward0>)
Epoch :  3200 Cost :  tensor(1.0809e-10, grad_fn=<MseLossBackward0>)
Epoch :  3600 Cost :  tensor(5.4263e-11, grad_fn=<MseLossBackward0>)
Epoch :  4000 Cost :  tensor(5.4263e-11, grad_fn=<MseLossBackward0>)
Epoch :  4400 Cost :  tensor(5.4263e-11, grad_fn=<MseLossBackward0>)
Epoch :  4800 Cost :  tensor(5.4263e-11, grad_fn=<MseLossBackward0>)
Epoch :  5200 Cost :  tensor(5.4263e-11, grad_fn=<MseLossBackward0>)
Epoch :  5600 Cost :  tensor(5.4263e-11, grad_fn=<

In [16]:
new_data=torch.FloatTensor([[10]])
pred_y=model(new_data)
print(pred_y)
print(list(model.parameters()))

tensor([[21.0000]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([1.0000], requires_grad=True)]


In [17]:
x_train =  torch.FloatTensor([[73,  80,  75], 
                                [93,  88, 93], 
                                [89,  91, 80], 
                                [96,  98, 100], 
                                [73,  66, 70]]) 
y_train =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [18]:
class MultiLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(3,1)

    def forward(self, x):
        return self.linear(x)

In [19]:
model=MultiLinearRegressionModel()
optimizer=optim.SGD(model.parameters(), lr=1e-6)

In [20]:
nb_epochs=20000
for epoch in range(nb_epochs):
    prediction=model(x_train)
    cost=F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0 :
        print('Epoch : ', epoch, 'Cost : ' ,cost)

Epoch :  0 Cost :  tensor(41675.6172, grad_fn=<MseLossBackward0>)
Epoch :  100 Cost :  tensor(11.4129, grad_fn=<MseLossBackward0>)
Epoch :  200 Cost :  tensor(5.4387, grad_fn=<MseLossBackward0>)
Epoch :  300 Cost :  tensor(5.4108, grad_fn=<MseLossBackward0>)
Epoch :  400 Cost :  tensor(5.3839, grad_fn=<MseLossBackward0>)
Epoch :  500 Cost :  tensor(5.3571, grad_fn=<MseLossBackward0>)
Epoch :  600 Cost :  tensor(5.3305, grad_fn=<MseLossBackward0>)
Epoch :  700 Cost :  tensor(5.3040, grad_fn=<MseLossBackward0>)
Epoch :  800 Cost :  tensor(5.2777, grad_fn=<MseLossBackward0>)
Epoch :  900 Cost :  tensor(5.2516, grad_fn=<MseLossBackward0>)
Epoch :  1000 Cost :  tensor(5.2256, grad_fn=<MseLossBackward0>)
Epoch :  1100 Cost :  tensor(5.1998, grad_fn=<MseLossBackward0>)
Epoch :  1200 Cost :  tensor(5.1740, grad_fn=<MseLossBackward0>)
Epoch :  1300 Cost :  tensor(5.1485, grad_fn=<MseLossBackward0>)
Epoch :  1400 Cost :  tensor(5.1231, grad_fn=<MseLossBackward0>)
Epoch :  1500 Cost :  tensor(5.0

In [21]:
new_data=torch.FloatTensor([[80,90,75]])
pred_y=model(new_data)
print(pred_y)
print(list(model.parameters()))

tensor([[169.3778]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[0.8652, 0.8891, 0.2638]], requires_grad=True), Parameter containing:
tensor([0.3560], requires_grad=True)]


In [22]:
data=np.loadtxt('data/data-01-test-score.csv', delimiter=',',dtype='float32')
x_data=data[:,0:-1]
t_data=data[:,[-1]]
x_train=torch.from_numpy(x_data)
t_train=torch.from_numpy(t_data)
print(x_train[:5])
print(t_train[:5])

tensor([[ 73.,  80.,  75.],
        [ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.]])
tensor([[152.],
        [185.],
        [180.],
        [196.],
        [142.]])


In [23]:
model=nn.Linear(3,1)
optimizer=optim.SGD(model.parameters(), lr=1e-6)
nb_epochs=20000

In [24]:
for epoch in range(nb_epochs):
    prediction=model(x_train)
    cost=F.mse_loss(prediction, t_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 400 == 0:
        print('Epoch : ', epoch, 'Cost : ',cost.item())

Epoch :  0 Cost :  20483.064453125
Epoch :  400 Cost :  13.15749740600586
Epoch :  800 Cost :  12.912622451782227
Epoch :  1200 Cost :  12.67624282836914
Epoch :  1600 Cost :  12.448132514953613
Epoch :  2000 Cost :  12.227924346923828
Epoch :  2400 Cost :  12.01537799835205
Epoch :  2800 Cost :  11.81018352508545
Epoch :  3200 Cost :  11.612161636352539
Epoch :  3600 Cost :  11.421015739440918
Epoch :  4000 Cost :  11.236520767211914
Epoch :  4400 Cost :  11.058409690856934
Epoch :  4800 Cost :  10.88650894165039
Epoch :  5200 Cost :  10.720602989196777
Epoch :  5600 Cost :  10.560410499572754
Epoch :  6000 Cost :  10.405821800231934
Epoch :  6400 Cost :  10.256567001342773
Epoch :  6800 Cost :  10.11253547668457
Epoch :  7200 Cost :  9.97348403930664
Epoch :  7600 Cost :  9.839259147644043
Epoch :  8000 Cost :  9.70970344543457
Epoch :  8400 Cost :  9.584613800048828
Epoch :  8800 Cost :  9.463932991027832
Epoch :  9200 Cost :  9.347383499145508
Epoch :  9600 Cost :  9.23491859436035

In [25]:
class MultiLinearRegressModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(3,1)

    def forward(self, x):
        return self.linear(x)

In [28]:
model=MultiLinearRegressModel()
optimizer=optim.SGD(model.parameters(), lr=1e-6)
nb_epochs=20000

In [29]:
for epoch in range(nb_epochs):
    prediction=model(x_train)
    cost=F.mse_loss(prediction, t_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 400==0:
        print('Epoch : ', epoch, 'Cost : ', cost.item())

Epoch :  0 Cost :  27026.970703125
Epoch :  400 Cost :  9.640527725219727
Epoch :  800 Cost :  9.535327911376953
Epoch :  1200 Cost :  9.433450698852539
Epoch :  1600 Cost :  9.334747314453125
Epoch :  2000 Cost :  9.239204406738281
Epoch :  2400 Cost :  9.146646499633789
Epoch :  2800 Cost :  9.057011604309082
Epoch :  3200 Cost :  8.970144271850586
Epoch :  3600 Cost :  8.885943412780762
Epoch :  4000 Cost :  8.80438232421875
Epoch :  4400 Cost :  8.725366592407227
Epoch :  4800 Cost :  8.648776054382324
Epoch :  5200 Cost :  8.574570655822754
Epoch :  5600 Cost :  8.502676963806152
Epoch :  6000 Cost :  8.433008193969727
Epoch :  6400 Cost :  8.365484237670898
Epoch :  6800 Cost :  8.30008316040039
Epoch :  7200 Cost :  8.23670768737793
Epoch :  7600 Cost :  8.175274848937988
Epoch :  8000 Cost :  8.115704536437988
Epoch :  8400 Cost :  8.05797290802002
Epoch :  8800 Cost :  8.001993179321289
Epoch :  9200 Cost :  7.947725296020508
Epoch :  9600 Cost :  7.895100116729736
Epoch :  10

In [30]:
new_data=torch.FloatTensor([[73,80,75]])
pred_y=model(new_data)
print(pred_y)
print(list(model.parameters()))

tensor([[153.0369]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[0.5184, 0.5412, 0.9586]], requires_grad=True), Parameter containing:
tensor([0.0041], requires_grad=True)]
