In [149]:
import torch

In [150]:
torch.tensor([[1,2],[3,4]])

tensor([[1, 2],
        [3, 4]])

In [151]:
x=torch.FloatTensor([[1,2,3],[4,5,6]])

In [152]:
print(torch.tensor([[1,2],[3,4]]))
#print(torch.tensor([[1,2],[3,4]]), device="cuda:0")
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [153]:
ft=torch.FloatTensor([[1,2],[3,4]])
lt=torch.LongTensor([[1,2],[3,4]])
bt=torch.ByteTensor([[1,2],[3,4]])
print(ft)
print(lt)
print(bt)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)


In [154]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x, type(x))

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>


In [155]:
tx=torch.from_numpy(x)
print(tx, type(tx))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=torch.int32) <class 'torch.Tensor'>


In [156]:
nx=tx.numpy()
print(nx, type(nx))

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>


In [157]:
ft=tx.float()
print(ft, type(ft))
lt=ft.long()
print(lt, type(lt))
bt=ft.byte()
print(bt)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]) <class 'torch.Tensor'>
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]) <class 'torch.Tensor'>
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=torch.uint8)


In [158]:
na=np.arange(1,13).reshape(3,2,2)
t=torch.from_numpy(na)
t

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)

In [159]:
a=np.arange(12).reshape(2,3,-1)
b=np.arange(2,14).reshape(2,3,-1)
c=np.arange(10,16).reshape(3,2)
ta=torch.from_numpy(a)
tb=torch.from_numpy(b)
tc=torch.from_numpy(c)
#print(ta)
print(ta.size())
print(tb.size())
print(tc.size())

torch.Size([2, 3, 2])
torch.Size([2, 3, 2])
torch.Size([3, 2])


In [160]:
print(ta+tc)

tensor([[[10, 12],
         [14, 16],
         [18, 20]],

        [[16, 18],
         [20, 22],
         [24, 26]]], dtype=torch.int32)


In [161]:
x=torch.arange(1,13)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [162]:
print(x.view(3,4))
print(x.reshape(3,4))
print(x.view(4,3))
print(x.view(3,2,2))

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])


In [163]:
x1=x.view(3,1,4)
print(x1)

tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12]]])


In [164]:
print(x1.squeeze())

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [165]:
print(x1.unsqueeze(1))
print(x1.size())

tensor([[[[ 1,  2,  3,  4]]],


        [[[ 5,  6,  7,  8]]],


        [[[ 9, 10, 11, 12]]]])
torch.Size([3, 1, 4])


In [166]:
x2=x.view(2,3,2)
x2

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])

In [167]:
print(x2[:,:,1])

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


In [168]:
x=torch.FloatTensor(4,10)
splits=x.split(3, dim=1)
for s in splits:
    print(s.size())

torch.Size([4, 3])
torch.Size([4, 3])
torch.Size([4, 3])
torch.Size([4, 1])


In [169]:
x=torch.arange(1,13).view(3,2,2)
x

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [170]:
index=torch.LongTensor([0])
y=x.index_select(dim=2, index=index)
y

tensor([[[ 1],
         [ 3]],

        [[ 5],
         [ 7]],

        [[ 9],
         [11]]])

In [171]:
x=torch.arange(1,65).view(4,2,4,2)
x

tensor([[[[ 1,  2],
          [ 3,  4],
          [ 5,  6],
          [ 7,  8]],

         [[ 9, 10],
          [11, 12],
          [13, 14],
          [15, 16]]],


        [[[17, 18],
          [19, 20],
          [21, 22],
          [23, 24]],

         [[25, 26],
          [27, 28],
          [29, 30],
          [31, 32]]],


        [[[33, 34],
          [35, 36],
          [37, 38],
          [39, 40]],

         [[41, 42],
          [43, 44],
          [45, 46],
          [47, 48]]],


        [[[49, 50],
          [51, 52],
          [53, 54],
          [55, 56]],

         [[57, 58],
          [59, 60],
          [61, 62],
          [63, 64]]]])

In [172]:
x=torch.arange(1,10).view(3,3)
y=torch.arange(11,20).view(3,3)
print(x)
print(y)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]])


In [173]:
z=torch.cat([x,y], dim=1)
z

tensor([[ 1,  2,  3, 11, 12, 13],
        [ 4,  5,  6, 14, 15, 16],
        [ 7,  8,  9, 17, 18, 19]])

In [174]:
z=torch.stack([x,y],dim=1)
print(z)

tensor([[[ 1,  2,  3],
         [11, 12, 13]],

        [[ 4,  5,  6],
         [14, 15, 16]],

        [[ 7,  8,  9],
         [17, 18, 19]]])


In [175]:
x=torch.arange(1,7).view(1,2,3)
print(x)
y=x.expand(2,2,3)
print(y)

tensor([[[1, 2, 3],
         [4, 5, 6]]])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])


In [176]:
x=torch.randperm(100)
x

tensor([59, 20, 19, 11, 64, 53, 83, 84, 18, 29, 35, 88, 57,  9, 76, 90,  0, 80,
        65, 66, 47, 49, 15, 78, 93, 38,  8, 69, 51,  6, 79, 27, 52, 23, 73, 70,
        92, 46, 94, 10, 85, 72, 58, 24, 13, 82, 50, 36, 34, 21,  1, 28, 75, 91,
        17, 48, 30, 40, 54, 33, 32,  5, 26, 63, 98, 25, 86, 44, 71, 56, 45, 87,
        62, 89, 41, 16,  2, 68, 67, 97, 74, 55, 37, 61,  4, 43, 60, 95, 14,  7,
        99, 42, 12, 39,  3, 31, 96, 81, 77, 22])

In [177]:
x=torch.randperm(3**3).view(3,3,-1)
x

tensor([[[19,  8, 22],
         [11,  0, 15],
         [ 1,  5, 13]],

        [[20, 26, 16],
         [ 2,  9, 23],
         [25, 18,  6]],

        [[ 4, 12, 21],
         [ 7, 24, 10],
         [17,  3, 14]]])

In [178]:
y=x.argmax(dim=-1)
y

tensor([[2, 2, 2],
        [1, 2, 0],
        [2, 1, 0]])

In [179]:
value, indices=torch.topk(x, k=1, dim=0)
print(value)
print(indices)

tensor([[[20, 26, 22],
         [11, 24, 23],
         [25, 18, 14]]])
tensor([[[1, 1, 0],
         [0, 2, 1],
         [1, 1, 2]]])


In [180]:
x=torch.randperm(9).view(3,3)
x


tensor([[8, 7, 2],
        [0, 1, 3],
        [4, 5, 6]])

In [181]:
mask=x<4
mask

tensor([[False, False,  True],
        [ True,  True,  True],
        [False, False, False]])

In [182]:
y=x.masked_fill(mask, value=-1)
y

tensor([[ 8,  7, -1],
        [-1, -1, -1],
        [ 4,  5,  6]])