In [1]:
import torch

In [5]:
torch.tensor([[1,2],[3,4]])

tensor([[1, 2],
        [3, 4]])

In [7]:
x=torch.FloatTensor([[1,2,3],[4,5,6]])

In [15]:
print(torch.tensor([[1,2],[3,4]]))
#print(torch.tensor([[1,2],[3,4]]), device="cuda:0")
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [17]:
ft=torch.FloatTensor([[1,2],[3,4]])
lt=torch.LongTensor([[1,2],[3,4]])
bt=torch.ByteTensor([[1,2],[3,4]])
print(ft)
print(lt)
print(bt)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)


In [20]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x, type(x))

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>


In [22]:
tx=torch.from_numpy(x)
print(tx, type(tx))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=torch.int32) <class 'torch.Tensor'>


In [26]:
nx=tx.numpy()
print(nx, type(nx))

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'>


In [33]:
ft=tx.float()
print(ft, type(ft))
lt=ft.long()
print(lt, type(lt))
bt=ft.byte()
print(bt)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]) <class 'torch.Tensor'>
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]) <class 'torch.Tensor'>
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], dtype=torch.uint8)


In [41]:
na=np.arange(1,13).reshape(3,2,2)
t=torch.from_numpy(na)
t

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]], dtype=torch.int32)