In [1]:
import torch
import torch.nn.functional as F

In [4]:
z=torch.FloatTensor([1,2,3])
y_hat=F.softmax(z, dim=0)
print(y_hat)
print(y_hat.sum())

tensor([0.0900, 0.2447, 0.6652])
tensor(1.)


In [9]:
z=torch.rand(3,5, requires_grad=True)
y_hat=F.softmax(z, dim=1)
print(y_hat)

print(y_hat.sum(dim=1))

tensor([[0.1509, 0.1093, 0.2410, 0.2325, 0.2663],
        [0.1198, 0.2818, 0.2303, 0.2154, 0.1527],
        [0.1451, 0.1991, 0.2654, 0.1724, 0.2180]], grad_fn=<SoftmaxBackward0>)
tensor([1.0000, 1.0000, 1.0000], grad_fn=<SumBackward1>)


In [14]:
y=torch.randint(5, (3,)).long()
print(y)
y_one_hot=torch.zeros_like(y_hat)
y_one_hot.scatter_(1,y.unsqueeze(1),1)
print(y_one_hot)

tensor([3, 4, 3])
tensor([[0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.]])


In [16]:
print(y.unsqueeze(1))

tensor([[3],
        [4],
        [3]])


In [17]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [18]:
torch.manual_seed(1)

In [20]:
x_data=[[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data=[2,2,2,1,1,1,0,0]
x_train=torch.FloatTensor(x_data)
y_train=torch.LongTensor(y_data)
print(x_train.shape)
print(y_train.shape)

torch.Size([8, 4])
torch.Size([8])


In [23]:
y_one_hot=torch.zeros(8,3)
y_one_hot.scatter_(1,y_train.unsqueeze(1),1)
print(y_one_hot)

tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])


In [24]:
W=torch.zeros((4,3), requires_grad=True)
b=torch.zeros((1,3), requires_grad=True)
optimizer=optim.SGD([W, b], lr=0.1)

In [27]:
n_epochs=10000
for epoch in range(n_epochs):
    y_hat=F.softmax(x_train.matmul(W)+b, dim=1)
    cost=(y_one_hot * -torch.log(y_hat)).sum(dim=1).mean()

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100 == 0:
        print('Epoch : ',epoch, 'Cost : ', cost.item())


Epoch :  0 Cost :  0.03978875279426575
Epoch :  100 Cost :  0.039412543177604675
Epoch :  200 Cost :  0.039043426513671875
Epoch :  300 Cost :  0.03868097439408302
Epoch :  400 Cost :  0.038325224071741104
Epoch :  500 Cost :  0.03797595947980881
Epoch :  600 Cost :  0.03763280808925629
Epoch :  700 Cost :  0.03729577362537384
Epoch :  800 Cost :  0.03696456551551819
Epoch :  900 Cost :  0.03663923218846321
Epoch :  1000 Cost :  0.03631956875324249
Epoch :  1100 Cost :  0.03600522503256798
Epoch :  1200 Cost :  0.03569631651043892
Epoch :  1300 Cost :  0.035392582416534424
Epoch :  1400 Cost :  0.03509405627846718
Epoch :  1500 Cost :  0.03480030223727226
Epoch :  1600 Cost :  0.03451148793101311
Epoch :  1700 Cost :  0.03422728180885315
Epoch :  1800 Cost :  0.03394775837659836
Epoch :  1900 Cost :  0.03367269039154053
Epoch :  2000 Cost :  0.03340194374322891
Epoch :  2100 Cost :  0.03313552588224411
Epoch :  2200 Cost :  0.03287333995103836
Epoch :  2300 Cost :  0.032615192234516144

In [28]:
model=nn.Linear(4,3)
optimizer=optim.SGD(model.parameters(), lr=0.1)
n_epochs=10000

In [30]:
for epoch in range(n_epochs):
    y_hat=model(x_train)
    cost=F.cross_entropy(y_hat, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch : ',epoch, 'Cost : ',cost.item())

Epoch :  0 Cost :  0.03986620903015137
Epoch :  100 Cost :  0.039488691836595535
Epoch :  200 Cost :  0.03911803662776947
Epoch :  300 Cost :  0.03875427320599556
Epoch :  400 Cost :  0.038397204130887985
Epoch :  500 Cost :  0.038046516478061676
Epoch :  600 Cost :  0.037702158093452454
Epoch :  700 Cost :  0.037363916635513306
Epoch :  800 Cost :  0.03703158348798752
Epoch :  900 Cost :  0.03670510649681091
Epoch :  1000 Cost :  0.03638418763875961
Epoch :  1100 Cost :  0.03606875613331795
Epoch :  1200 Cost :  0.03575872629880905
Epoch :  1300 Cost :  0.035454075783491135
Epoch :  1400 Cost :  0.03515426442027092
Epoch :  1500 Cost :  0.03485958278179169
Epoch :  1600 Cost :  0.03456980362534523
Epoch :  1700 Cost :  0.03428470343351364
Epoch :  1800 Cost :  0.034004174172878265
Epoch :  1900 Cost :  0.03372815623879433
Epoch :  2000 Cost :  0.03345663473010063
Epoch :  2100 Cost :  0.03318936377763748
Epoch :  2200 Cost :  0.032926201820373535
Epoch :  2300 Cost :  0.03266727179288

In [32]:
prodiction = model(x_train)
print(prodiction)

tensor([[-13.8962,  -0.0880,  14.2799],
        [ -4.5370,   0.2184,   4.8439],
        [-22.3918,   9.9873,  13.8135],
        [-14.7454,  10.1718,   6.2298],
        [  0.7467,   3.9789,  -2.5304],
        [  4.6776,   8.5618, -10.6200],
        [  8.2611,   5.2696, -10.9009],
        [ 12.3500,   6.3167, -15.5665]], grad_fn=<AddmmBackward0>)


In [33]:
class SoftmaxClassModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(4,3)

    def forward(self, x):
        return self.linear(x)

In [34]:
model=SoftmaxClassModel()
optimizer=optim.SGD(model.parameters(), lr=0.1)
n_epochs=10000

In [35]:
for epoch in range(n_epochs):
    y_hat=model(x_train)
    cost=F.cross_entropy(y_hat, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch : ',epoch, "Cost : ",cost.item())

Epoch :  0 Cost :  2.637636423110962
Epoch :  100 Cost :  0.6479030251502991
Epoch :  200 Cost :  0.5646426677703857
Epoch :  300 Cost :  0.5110434293746948
Epoch :  400 Cost :  0.4672488868236542
Epoch :  500 Cost :  0.4282805621623993
Epoch :  600 Cost :  0.391924113035202
Epoch :  700 Cost :  0.35674208402633667
Epoch :  800 Cost :  0.32157716155052185
Epoch :  900 Cost :  0.28561723232269287
Epoch :  1000 Cost :  0.2508176863193512
Epoch :  1100 Cost :  0.23210185766220093
Epoch :  1200 Cost :  0.22086557745933533
Epoch :  1300 Cost :  0.21063703298568726
Epoch :  1400 Cost :  0.20127873122692108
Epoch :  1500 Cost :  0.19268494844436646
Epoch :  1600 Cost :  0.18476678431034088
Epoch :  1700 Cost :  0.17744912207126617
Epoch :  1800 Cost :  0.17066752910614014
Epoch :  1900 Cost :  0.16436627507209778
Epoch :  2000 Cost :  0.1584969311952591
Epoch :  2100 Cost :  0.1530178040266037
Epoch :  2200 Cost :  0.14789187908172607
Epoch :  2300 Cost :  0.14308682084083557
Epoch :  2400 Co

In [36]:
prediction=model(x_train)
print(prediction)

tensor([[-11.5036,  -0.2332,  11.5479],
        [ -4.5121,   0.3314,   4.2517],
        [-18.6580,   8.3967,  11.5297],
        [-13.0537,   8.7771,   5.5310],
        [  0.2068,   2.7514,  -3.0321],
        [  3.6674,   6.8846,  -8.6047],
        [  6.2557,   3.9119,  -9.5963],
        [  9.5301,   4.7041, -13.5656]], grad_fn=<AddmmBackward0>)
