In [1]:
import torch
import torch.nn.functional as F

In [4]:
z=torch.FloatTensor([1,2,3])
y_hat=F.softmax(z, dim=0)
print(y_hat)
print(y_hat.sum())

tensor([0.0900, 0.2447, 0.6652])
tensor(1.)


In [9]:
z=torch.rand(3,5, requires_grad=True)
y_hat=F.softmax(z, dim=1)
print(y_hat)

print(y_hat.sum(dim=1))

tensor([[0.1509, 0.1093, 0.2410, 0.2325, 0.2663],
        [0.1198, 0.2818, 0.2303, 0.2154, 0.1527],
        [0.1451, 0.1991, 0.2654, 0.1724, 0.2180]], grad_fn=<SoftmaxBackward0>)
tensor([1.0000, 1.0000, 1.0000], grad_fn=<SumBackward1>)


In [14]:
y=torch.randint(5, (3,)).long()
print(y)
y_one_hot=torch.zeros_like(y_hat)
y_one_hot.scatter_(1,y.unsqueeze(1),1)
print(y_one_hot)

tensor([3, 4, 3])
tensor([[0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.]])


In [16]:
print(y.unsqueeze(1))

tensor([[3],
        [4],
        [3]])


In [17]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [18]:
torch.manual_seed(1)

In [20]:
x_data=[[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data=[2,2,2,1,1,1,0,0]
x_train=torch.FloatTensor(x_data)
y_train=torch.LongTensor(y_data)
print(x_train.shape)
print(y_train.shape)

torch.Size([8, 4])
torch.Size([8])


In [23]:
y_one_hot=torch.zeros(8,3)
y_one_hot.scatter_(1,y_train.unsqueeze(1),1)
print(y_one_hot)

tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])


In [24]:
W=torch.zeros((4,3), requires_grad=True)
b=torch.zeros((1,3), requires_grad=True)
optimizer=optim.SGD([W, b], lr=0.1)

In [26]:
n_epochs=10000
for epoch in range(n_epochs):
    y_hat=F.softmax(x_train.matmul(W)+b, dim=1)
    cost=(y_one_hot * -torch.log(y_hat)).sum(dim=1).mean()

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100 == 0:
        print('Epoch : ',epoch, 'Cost : ', cost.item())


Epoch :  0 Cost :  1.0986123085021973
Epoch :  100 Cost :  0.7041996121406555
Epoch :  200 Cost :  0.6229995489120483
Epoch :  300 Cost :  0.5657169222831726
Epoch :  400 Cost :  0.5152913331985474
Epoch :  500 Cost :  0.467661589384079
Epoch :  600 Cost :  0.4212779700756073
Epoch :  700 Cost :  0.37540146708488464
Epoch :  800 Cost :  0.3297656178474426
Epoch :  900 Cost :  0.2850724160671234
Epoch :  1000 Cost :  0.24815461039543152
Epoch :  1100 Cost :  0.23267605900764465
Epoch :  1200 Cost :  0.22139872610569
Epoch :  1300 Cost :  0.2111290991306305
Epoch :  1400 Cost :  0.2017364501953125
Epoch :  1500 Cost :  0.19311320781707764
Epoch :  1600 Cost :  0.18516962230205536
Epoch :  1700 Cost :  0.177829310297966
Epoch :  1800 Cost :  0.17102722823619843
Epoch :  1900 Cost :  0.16470743715763092
Epoch :  2000 Cost :  0.1588211953639984
Epoch :  2100 Cost :  0.15332652628421783
Epoch :  2200 Cost :  0.14818623661994934
Epoch :  2300 Cost :  0.1433679759502411
Epoch :  2400 Cost :  0